import type { BasicSpeakCardItem } from "../types/basicSpeakType";

export const BASIC_SPEAK_CARDS: BasicSpeakCardItem[] = [
  {
    id: "vowel-a",
    title: "아",
    subtitle: "아",
    category: "모음",
    description: "기초 모음 '아' 소리를 또렷하게 시작하는 연습",
    guideText: "입을 자연스럽게 열고 '아' 소리를 천천히 내어보세요.",
  },
  {
    id: "vowel-ya",
    title: "야",
    subtitle: "야",
    category: "모음",
    description: "입 모양을 유지하며 '야' 소리를 분명하게 연습",
    guideText: "'이'에서 '아'로 넘어가듯 부드럽게 발음해보세요.",
  },
  {
    id: "vowel-eo",
    title: "어",
    subtitle: "어",
    category: "모음",
    description: "편안한 입모양으로 '어' 발음을 안정적으로 연습",
    guideText: "입을 과하게 벌리지 않고 편안하게 '어'를 내어보세요.",
  },
  {
    id: "vowel-yeo",
    title: "여",
    subtitle: "여",
    category: "모음",
    description: "'여' 발음의 시작과 끝을 분명하게 구분하는 연습",
    guideText: "혀의 움직임을 가볍게 유지하며 또렷하게 소리 내보세요.",
  },
  {
    id: "consonant-ieung",
    title: "ㅇ",
    subtitle: "응(이응)",
    category: "자음",
    description: "이응 소리를 안정적으로 이어가는 기초 훈련",
    guideText: "코와 목에 힘을 빼고 부드럽게 울림을 느껴보세요.",
  },
  {
    id: "consonant-eul",
    title: "ㅇ",
    subtitle: "(이을)",
    category: "자음",
    description: "가벼운 울림과 함께 발성의 흐름을 느끼는 연습",
    guideText: "짧고 또렷하게 반복하며 입과 혀의 움직임을 확인해보세요.",
  },
  {
    id: "consonant-giyeok",
    title: "ㄱ",
    subtitle: "(기역)",
    category: "자음",
    description: "혀뿌리와 입천장의 접촉을 느끼는 기초 자음 훈련",
    guideText: "'그'가 아니라 'ㄱ'의 시작 느낌에 집중해보세요.",
  },
  {
    id: "consonant-nieun",
    title: "ㄴ",
    subtitle: "니은",
    category: "자음",
    description: "혀끝 위치를 느끼며 안정적으로 소리 내는 연습",
    guideText: "혀끝이 윗잇몸에 닿는 느낌을 의식해보세요.",
  },
  {
    id: "consonant-digeut",
    title: "ㄷ",
    subtitle: "디귿",
    category: "자음",
    description: "짧고 분명한 'ㄷ' 소리를 연습하는 카드",
    guideText: "혀끝을 가볍게 붙였다 떼며 리듬감 있게 발음해보세요.",
  },
  {
    id: "consonant-rieul",
    title: "ㄹ",
    subtitle: "리을",
    category: "자음",
    description: "'ㄹ'의 혀 움직임을 부드럽게 익히는 연습",
    guideText: "혀를 너무 세게 치지 말고 가볍게 튕기듯 연습해보세요.",
  },
  {
    id: "repeat-ga",
    title: "가, 가, 가",
    subtitle: "가 반복",
    category: "반복 발성",
    description: "짧은 반복 발성으로 리듬과 명료도를 익히는 연습",
    guideText: "속도보다 일정한 리듬으로 반복하는 데 집중해보세요.",
  },
  {
    id: "repeat-na",
    title: "나, 나, 나",
    subtitle: "나 반복",
    category: "반복 발성",
    description: "같은 소리를 반복하며 입과 혀의 움직임을 익히는 연습",
    guideText: "한 번씩 또렷하게 구분해서 발음해보세요.",
  },
  {
    id: "repeat-da",
    title: "다, 다, 다",
    subtitle: "다 반복",
    category: "반복 발성",
    description: "짧고 분명한 발음의 시작을 익히는 반복 훈련",
    guideText: "소리의 시작점을 분명하게 만들어보세요.",
  },
  {
    id: "repeat-ra",
    title: "라, 라, 라",
    subtitle: "라 반복",
    category: "반복 발성",
    description: "리을 계열 발음을 반복하며 자연스럽게 연결하는 연습",
    guideText: "혀를 가볍게 움직이며 긴장하지 않고 발음해보세요.",
  },
  {
    id: "repeat-ma",
    title: "마, 마, 마",
    subtitle: "마 반복",
    category: "반복 발성",
    description: "입술 닫힘과 개방을 느끼며 발화의 시작을 연습",
    guideText: "입술이 닫혔다 열리는 감각을 천천히 확인해보세요.",
  },
];

export const getBasicSpeakCardById = (cardId?: string) =>
  BASIC_SPEAK_CARDS.find((card) => card.id === cardId);